spring:
  application:
    name: customer

  datasource:
    username: postgres
    password: postgres
    url: jdbc:p6spy:postgresql://localhost:5432/demo
    #    driver-class-name: org.postgresql.Driver
    driver-class-name: com.p6spy.engine.spy.P6SpyDriver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 512
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000

  jpa:
    #    properties:
    #      hibernate:
    #        jdbc.batch_size: 100  # 한 번에 INSERT할 최대 Batch 크기
    #        order_inserts: true   # INSERT 쿼리를 같은 엔티티끼리 그룹화
    #        order_updates: true   # UPDATE 쿼리를 같은 엔티티끼리 그룹화
    #        batch_versioned_data: true # 버전 필드를 포함한 엔티티도 배치 처리
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  sql:
    init:
      mode: never